# -*- coding: utf-8 -*-
"""b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkvdIOylFQNZoLjdtMHNH2v4EPJ0H45-
"""

import os
from tqdm import tqdm
packages = [
            "git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /root/vorst-cavry",
]
for install in tqdm(packages, desc=print("Memulai awal...")):
    os.system(install)