# -*- coding: utf-8 -*-
"""kivotos-SDXL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkvdIOylFQNZoLjdtMHNH2v4EPJ0H45-
"""

# Commented out IPython magic to ensure Python compatibility.
from IPython import get_ipython
from IPython.display import display
import os
import subprocess
from tqdm import tqdm
packages = [
            "apt-get install -y python3.10-venv",
            "pip install spaces",
]
for install in tqdm(packages, desc=print("Tunggu aja...")):
    os.system(install)
ROOT_DIR = "/content"
REPO_URL = "https://huggingface.co/spaces/Linaqruf/kivotos-xl-2.0"
REPO_DIR = os.path.join(ROOT_DIR, "kivotos-xl-2.0")

os.environ["HF_TOKEN"] = ""
os.environ["ENABLE_REFINER_PROMPT"] = "1"

def clone(url, dir, branch=None):
    subprocess.check_call(["git", "clone", url, dir], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if branch:
        subprocess.check_call(["git", "checkout", branch], cwd=dir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def install_deps(dir):
    subprocess.check_call(["pip", "install", "-r", "requirements.txt", "--cache-dir", "./.cache"], cwd=dir)

def main():
    if not os.path.exists(REPO_DIR):
        print(f"Cloning Repository to {REPO_DIR}")
        clone(REPO_URL, REPO_DIR)
        print(f"Installing required python libraries")
        install_deps(REPO_DIR)
        print("Done!")

    os.chdir(REPO_DIR)
    !python -m venv .venv
    !source .venv/bin/activate
#     %cd /content/kivotos-xl-2.0
    !python app.py

if __name__ == "__main__":
    main()