# -*- coding: utf-8 -*-
"""short.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkvdIOylFQNZoLjdtMHNH2v4EPJ0H45-
"""

import os
from tqdm import tqdm
packages = [
            "git clone https://github.com/vorstcavry/vorstcavry-tunnels /root/vorst-cavry/extensions/tunnels",
            "aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/vorstcavry/test/resolve/main/styles.csv -d /root/vorst-cavry -o styles.csv",
            "aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/embed/upscale/resolve/main/4x-UltraSharp.pth -d /root/vorst-cavry/models/ESRGAN -o 4x-UltraSharp.pth",
            "wget https://raw.githubusercontent.com/vorstcavry/s-scripts/main/run_n_times.py -O /root/vorst-cavry/scripts/run_n_times.py"
]
for install in tqdm(packages, desc=print("Install tunnel dan runtime script...")):
    os.system(install)

import os
from tqdm import tqdm
packages = [
            "git clone https://github.com/vorstcavry/embeddings /root/vorst-cavry/embeddings/negative",
            "git clone https://github.com/vorstcavry/Checkpoint-Model /root/vorst-cavry/models/Stable-diffusion/Checkpoint-Model",
            "git clone https://github.com/vorstcavry/ncpt_colab_timer /root/vorst-cavry/extensions/ncpt_colab_timer",
            "git clone https://github.com/vorstcavry/static /root/vorst-cavry/static"
]
for install in tqdm(packages, desc=print("Install Bahan tambahan...")):
    os.system(install)


import os
from tqdm import tqdm
packages = [
            "rm -rf /root/vorst-cavry/models/Stable-diffusion/Checkpoint-Model/.git",
            "rm -rf /root/vorst-cavry/embeddings/negative/.git",
]
for install in tqdm(packages, desc=print("Menghapus bahan yang tidak dibutuhkan...")):
    os.system(install)